[project]
name = "my-bin"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.5"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.0.17",
]
